{% set name = "graphblas-algorithms" %}
{% set version = "2023.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/graphblas-algorithms-{{ version }}.tar.gz
  sha256: 059be9faaef2697a1d29e4fd50ae11a6ee6d91bb6c1c341f6138121aca4b40f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-git-versioning
    - pip
  run:
    - python >={{ python_min }}
    - python-graphblas >=2023.1.0

test:
  imports:
    - graphblas_algorithms
  commands:
    - pip check
    # - pytest -v --pyargs graphblas_algorithms
  requires:
    - pip
    # - pytest
    # - networkx >=3.0
    - python {{ python_min }}

about:
  home: https://github.com/python-graphblas/graphblas-algorithms
  summary: Fast graph algorithms written in GraphBLAS
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Fast graph algorithms written in Python with `python-graphblas` targeting the
    NetworkX API and may be used as a backend to NetworkX 3.0 via dispatching.
  dev_url: https://github.com/python-graphblas/graphblas-algorithms

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
